#!/bin/bash
# params $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20}
XSERVER="$1"
XGROUP="$2"
XGPASS="$3"
XUSER="$4"
XPASS="$5"
cp /etc/vpnc/gvpnc.conf /etc/vpnc/gvpnc.conf.backup >/dev/null 2>&1
rm -f /etc/vpnc/gvpnc.conf >/dev/null 2>&1
touch /etc/vpnc/gvpnc.conf
echo -e "# AUTOGENERATED BY gvpnc" >> "/etc/vpnc/gvpnc.conf"
echo -e "IPSec gateway $1" >> "/etc/vpnc/gvpnc.conf"
echo -e "IPSec ID $2" >> "/etc/vpnc/gvpnc.conf"
echo -e "IPSec secret $3" >> "/etc/vpnc/gvpnc.conf"
echo -e "Xauth username $4" >> "/etc/vpnc/gvpnc.conf"
echo -e "Xauth password $5" >> "/etc/vpnc/gvpnc.conf"
# DEBUG --> echo "OK"
# vpnc-connect "/etc/vpnc/gvpnc.conf"
vpnc "/etc/vpnc/gvpnc.conf"
